// Natalia Heller — catalog data (Spanish copy)

const NH_CATEGORIES = [
  { slug: 'todos', label: 'Todos' },
  { slug: 'ceramica', label: 'Cerámica' },
  { slug: 'acuarela', label: 'Acuarelas' },
  { slug: 'gouache', label: 'Gouache' },
  { slug: 'textil', label: 'Textiles' },
  { slug: 'ilustracion', label: 'Ilustraciones' },
  { slug: 'mixta', label: 'Técnica mixta' },
  { slug: 'stickers', label: 'Stickers' },
  { slug: 'laminas', label: 'Láminas' },
  { slug: 'mandalas', label: 'Mandalas' },
  { slug: 'abanicos', label: 'Abanicos' },
];

const NH_PRODUCTS = [
  {
    slug: 'helecho-i', title: 'Helecho I',
    category: 'laminas', cat_label: 'Lámina — Giclée',
    price: 8500, size: 'A4 · 21×29,7 cm',
    tone: 'a', tall: 1.3,
    medium: 'Impresión giclée sobre papel Hahnemühle 308g',
    edition: 'Edición abierta · firmada',
    desc: 'Estudio de helecho a tinta, parte de la serie de botánica sensible de 2025. Cada lámina se firma a mano en el dorso.',
    sizes: ['A6', 'A5', 'A4', 'A3'],
    frame: true,
  },
  {
    slug: 'cuenco-musgo', title: 'Cuenco Musgo',
    category: 'ceramica', cat_label: 'Cerámica — Gres esmaltado',
    price: 24000, size: '∅ 14 cm · 6 cm alto',
    tone: 'b', tall: 1,
    medium: 'Gres cocido a 1240°, esmalte ceniza de madera',
    edition: 'Pieza única',
    desc: 'Cuenco tornado a mano, esmaltado con ceniza propia. Superficie porosa, irregular, cálida al tacto.',
    sizes: null, frame: false,
  },
  {
    slug: 'anemone-studio', title: 'Anémonas — estudio',
    category: 'acuarela', cat_label: 'Acuarela original',
    price: 46000, size: '24×32 cm',
    tone: 'c', tall: 1.25,
    medium: 'Acuarela sobre papel Arches 300g',
    edition: 'Obra original',
    desc: 'Estudio libre de anémonas de campo. Pigmentos en capas delgadas, dejando respirar el blanco del papel.',
    sizes: null, frame: true,
  },
  {
    slug: 'tapiz-raiz', title: 'Tapiz Raíz',
    category: 'textil', cat_label: 'Fibra — telar manual',
    price: 92000, size: '38×62 cm',
    tone: 'd', tall: 1.5,
    medium: 'Lana cruda teñida con cebolla y yerba mate',
    edition: 'Pieza única',
    desc: 'Tejido en telar de alto lizo. Tonos cálidos obtenidos con tintes naturales cultivados en el estudio.',
    sizes: null, frame: false,
  },
  {
    slug: 'gouache-membrillo', title: 'Membrillo en gouache',
    category: 'gouache', cat_label: 'Gouache original',
    price: 38000, size: '18×24 cm',
    tone: 'e', tall: 1.1,
    medium: 'Gouache sobre papel de algodón',
    edition: 'Obra original · enmarcable',
    desc: 'Estudio de membrillo maduro pintado del natural en el huerto del estudio.',
    sizes: null, frame: true,
  },
  {
    slug: 'abanico-jazmin', title: 'Abanico Jazmín',
    category: 'abanicos', cat_label: 'Abanico pintado a mano',
    price: 28000, size: '23 cm plegado',
    tone: 'f', tall: 0.95,
    medium: 'Madera de peral y algodón, pintado en tinta india',
    edition: 'Serie de 8',
    desc: 'Abanico clásico pintado a mano con jazmines, cada uno ligeramente distinto.',
    sizes: null, frame: false,
  },
  {
    slug: 'stickers-botanicos', title: 'Stickers botánicos',
    category: 'stickers', cat_label: 'Set de 6 stickers',
    price: 4500, size: 'Entre 4 y 8 cm',
    tone: 'a', tall: 0.9,
    medium: 'Vinilo mate resistente al agua',
    edition: 'Producción continua',
    desc: 'Set de seis stickers con motivos de la serie de botánica. Ideales para cuadernos, notebooks y termos.',
    sizes: null, frame: false,
  },
  {
    slug: 'mandala-ornamental', title: 'Mandala ornamental — hoja',
    category: 'mandalas', cat_label: 'Lámina para pintar',
    price: 3800, size: 'A4',
    tone: 'b', tall: 1.2,
    medium: 'Impresión en papel marfil 150g',
    edition: 'Producción continua',
    desc: 'Lámina ornamental de línea fina, pensada para pintar con lápices o acuarelas.',
    sizes: ['A5', 'A4', 'A3'], frame: false,
  },
  {
    slug: 'ilustracion-paloma', title: 'Paloma en línea fina',
    category: 'ilustracion', cat_label: 'Ilustración original',
    price: 32000, size: '20×28 cm',
    tone: 'c', tall: 1.3,
    medium: 'Tinta sobre papel',
    edition: 'Obra original',
    desc: 'Ilustración a tinta en trazo continuo. Estudio del gesto de una paloma en reposo.',
    sizes: null, frame: true,
  },
  {
    slug: 'mixta-herbario', title: 'Herbario II',
    category: 'mixta', cat_label: 'Técnica mixta',
    price: 54000, size: '30×40 cm',
    tone: 'd', tall: 1.15,
    medium: 'Collage, acuarela y costura a mano sobre papel',
    edition: 'Obra original',
    desc: 'Pieza de la serie Herbario: plantas prensadas del huerto intervenidas con acuarela y costura.',
    sizes: null, frame: true,
  },
  {
    slug: 'taza-ceniza', title: 'Taza Ceniza',
    category: 'ceramica', cat_label: 'Cerámica — taza',
    price: 18000, size: '300 ml',
    tone: 'e', tall: 1,
    medium: 'Gres tornado, esmalte mate',
    edition: 'Serie pequeña',
    desc: 'Taza de morning coffee, ligera en la mano, borde suave. Cada una con su huella.',
    sizes: null, frame: false,
  },
  {
    slug: 'lamina-olivo', title: 'Olivo',
    category: 'laminas', cat_label: 'Lámina — Giclée',
    price: 8500, size: 'A4',
    tone: 'f', tall: 1.25,
    medium: 'Impresión giclée sobre papel Hahnemühle 308g',
    edition: 'Edición abierta · firmada',
    desc: 'Rama de olivo en tinta, trazo único. De la serie Botánica sensible.',
    sizes: ['A6', 'A5', 'A4', 'A3'], frame: true,
  },
];

// Tattoo portfolio — masonry with sketches + on-skin
const NH_TATTOOS = [
  { tone: 'a', tall: 1.4, label: 'BOCETO · 2025', kind: 'Helecho antebrazo' },
  { tone: 'd', tall: 0.9, label: 'EN PIEL', kind: 'Rama de olivo · clavícula' },
  { tone: 'c', tall: 1.2, label: 'BOCETO', kind: 'Ornamental · esternón' },
  { tone: 'b', tall: 1.6, label: 'EN PIEL', kind: 'Flor silvestre · espalda' },
  { tone: 'e', tall: 1.1, label: 'BOCETO · 2024', kind: 'Serie luna + hojas' },
  { tone: 'f', tall: 1.35, label: 'EN PIEL', kind: 'Colibrí en línea fina' },
  { tone: 'd', tall: 1, label: 'BOCETO', kind: 'Jazmín del país · brazo' },
  { tone: 'a', tall: 1.45, label: 'EN PIEL', kind: 'Mandala minimal · muñeca' },
  { tone: 'c', tall: 0.95, label: 'BOCETO', kind: 'Hoja monstera · tobillo' },
  { tone: 'b', tall: 1.3, label: 'EN PIEL', kind: 'Ornamental pecho' },
];

Object.assign(window, { NH_CATEGORIES, NH_PRODUCTS, NH_TATTOOS });
